# Pytorch Basics

## Tensors

Tensors are similar to NumPy’s `ndarray`s, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [0]:
from __future__ import print_function
import torch

In [34]:
torch.__version__

'1.4.0'

In [35]:
x = torch.empty(5, 3) # Construct a 5x3 matrix, uninitialized:
x

tensor([[9.3040e+30, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.4721e+21, 3.0104e+29, 7.1853e+22],
        [7.1901e+28, 6.2706e+22, 4.7428e+30],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [36]:
x = torch.rand(5, 3) # Construct a randomly initialized matrix:
x

tensor([[0.7618, 0.6457, 0.5922],
        [0.9466, 0.0442, 0.8821],
        [0.9491, 0.5761, 0.8488],
        [0.5377, 0.9906, 0.0024],
        [0.7579, 0.1301, 0.5631]])

In [37]:
# Construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long) 
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [38]:
# Construct a tensor directly from data
x = torch.tensor([5., 3])
print(x)
print(x.dtype)

tensor([5., 3.])
torch.float32


Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, **unless new values are provided by user**

In [39]:
x = x.new_ones(5, 3) # new_* methods take in sizes
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
x.dtype

torch.float32

In [41]:
x = torch.randn_like(x, dtype=torch.float) # same size, but override dtype
x

tensor([[-1.1059, -2.0536,  0.3040],
        [ 0.3142, -2.5831, -0.0914],
        [-0.6634,  1.6380,  0.8254],
        [-0.8186,  0.1152,  0.2913],
        [ 1.5138, -0.6156, -0.1211]])

In [42]:
x.size()

torch.Size([5, 3])

> Note: torch.Size is in fact a `tuple`, so it supports all `tuple` operations.

In [43]:
num_row, num_col = x.size()
print(f'#rows: {num_row}, #cols: {num_col}')

#rows: 5, #cols: 3


In [44]:
x.shape

torch.Size([5, 3])

In [45]:
x.ndim

2

## Operations

There are multiple syntaxes for operations. For example, addition:

- Syntax 1

In [46]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.2049, -1.9861,  0.9163],
        [ 0.8520, -2.0157,  0.3516],
        [-0.0578,  1.7082,  0.9780],
        [-0.0180,  0.7752,  1.0192],
        [ 1.5163, -0.0810,  0.1910]])


- Syntax 2

In [47]:
print(torch.add(x, y))

tensor([[-0.2049, -1.9861,  0.9163],
        [ 0.8520, -2.0157,  0.3516],
        [-0.0578,  1.7082,  0.9780],
        [-0.0180,  0.7752,  1.0192],
        [ 1.5163, -0.0810,  0.1910]])


Providing an output tensor as argument

In [48]:
result = torch.empty(x.size())
torch.add(x, y, out=result)
result

tensor([[-0.2049, -1.9861,  0.9163],
        [ 0.8520, -2.0157,  0.3516],
        [-0.0578,  1.7082,  0.9780],
        [-0.0180,  0.7752,  1.0192],
        [ 1.5163, -0.0810,  0.1910]])

Any operation that mutates a tensor in-place is post-fixed with an `_`.

In-place addition:

In [49]:
# add x to y
y.add_(x)
y

tensor([[-0.2049, -1.9861,  0.9163],
        [ 0.8520, -2.0157,  0.3516],
        [-0.0578,  1.7082,  0.9780],
        [-0.0180,  0.7752,  1.0192],
        [ 1.5163, -0.0810,  0.1910]])

Use standard NumPy-like indexing 

In [50]:
x[::2, :]

tensor([[-1.1059, -2.0536,  0.3040],
        [-0.6634,  1.6380,  0.8254],
        [ 1.5138, -0.6156, -0.1211]])

For one element tensor, use `.item()` to get the value as a Python number

In [51]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4443])
-0.44426143169403076


## Numpy Bridge

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Torch Tensor $\rightarrow$ Numpy Array

In [52]:
torch_tensor = torch.ones(5, 1)
torch_tensor

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [53]:
np_array = torch_tensor.numpy()
np_array

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [54]:
torch_tensor.add_(2)
print(torch_tensor)
print(np_array)

tensor([[3.],
        [3.],
        [3.],
        [3.],
        [3.]])
[[3.]
 [3.]
 [3.]
 [3.]
 [3.]]


### Numpy Array $\rightarrow$ Torch Tensor

In [55]:
import numpy as np

np_array = np.ones(5)
torch_tensor = torch.from_numpy(np_array)

print(np_array)
print(torch_tensor)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [56]:
np.add(np_array, 1, out=np_array)
print(np_array)
print(torch_tensor)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [57]:
!nvidia-smi

Thu Apr 23 20:15:19 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P0    24W /  75W |    535MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [58]:
torch.cuda.is_available()

True

In [59]:
# Run this cell only if CUDA is available
# Use `torch.device` objects to move tensors in and out of GPU
if torch.cuda.is_available():
  device = torch.device('cuda') # a CUDA device object
  y = torch.ones_like(x, device=device) # directly create a tensor on GPU
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to('cpu', torch.double)) # ``.to`` can also change dtype together

tensor([0.5557], device='cuda:0')
tensor([0.5557], dtype=torch.float64)
