# Torch and Numpy

In [0]:
import torch
import numpy as np

In [4]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data) # np -> torch
tensor2arr = torch_data.numpy() # torch -> np

print('numpy array:\n', np_data)
print('torch tensor:\n', torch_data)
print('torch -> np:\n', tensor2arr)


numpy array:
 [[0 1 2]
 [3 4 5]]
torch tensor:
 tensor([[0, 1, 2],
        [3, 4, 5]])
torch -> np:
 [[0 1 2]
 [3 4 5]]


## Math operations

Operations of PyTorch's tensor is very similar to the array in Numpy.

In [10]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data) # convert to Float32

# absolute value
print('abs:')
print('numpy:', np.abs(data))
print('torch:', torch.abs(tensor))

# mean
print('\nmean:')
print('numpy:', np.mean(data))
print('torch:', torch.mean(tensor))

abs:
numpy: [1 2 1 2]
torch: tensor([1., 2., 1., 2.])

mean:
numpy: 0.0
torch: tensor(0.)


Matrix operation:

In [11]:
data = np.arange(1, 5).reshape((2, 2))
data

array([[1, 2],
       [3, 4]])

In [17]:
tensor = torch.from_numpy(data)
tensor

tensor([[1, 2],
        [3, 4]])

Matrix multiplication in Numpy:

In [14]:
data.dot(data)

array([[ 7, 10],
       [15, 22]])

In [15]:
data @ data

array([[ 7, 10],
       [15, 22]])

In [18]:
np.dot(data, data)

array([[ 7, 10],
       [15, 22]])

Matrix multiplication in PyTorch:

In [20]:
torch.matmul(tensor, tensor)

tensor([[ 7, 10],
        [15, 22]])

In [21]:
torch.mm(tensor, tensor)

tensor([[ 7, 10],
        [15, 22]])