# `Variable`

In [0]:
import torch
from torch.autograd import Variable

In [0]:
tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True)

In [6]:
tensor

tensor([[1., 2.],
        [3., 4.]])

In [12]:
variable

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

## `Variable` in autograd

In [0]:
t_out = torch.mean(tensor * tensor)
v_out = torch.mean(variable * variable)

In [8]:
t_out

tensor(7.5000)

In [9]:
v_out

tensor(7.5000, grad_fn=<MeanBackward0>)

In [0]:
v_out.backward()

In [11]:
variable.grad

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

## Get data from `Variable`

In [13]:
variable

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [14]:
variable.data

tensor([[1., 2.],
        [3., 4.]])

In [15]:
variable.data.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)